<?php

namespace ClubProBundle\Repository;

/**
 * SoussecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoussecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
