<?php

namespace ClubProBundle\Repository;

/**
 * TypeclientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeclientRepository extends \Doctrine\ORM\EntityRepository
{
}
